apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadowsocks-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shadowsocks-operator
  template:
    metadata:
      labels:
        name: shadowsocks-operator
    spec:
      serviceAccountName: shadowsocks-operator
      containers:
        - name: shadowsocks-operator
          # Replace this with the built image name
          image: danielxlee/shadowsocks-operator:v0.0.1
          command:
          - shadowsocks-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "shadowsocks-operator"
